// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/pending": {
    params: {};
  };
  "/banned": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/api/admin/approve": {
    params: {};
  };
  "/api/admin/change-role": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/api/auth/callback/authentik": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/pending" | "/banned" | "/admin" | "/api/admin/approve" | "/api/admin/change-role" | "/auth/login" | "/api/auth/callback/authentik" | "/auth/logout";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/pending.tsx": {
    id: "routes/pending";
    page: "/pending";
  };
  "routes/banned.tsx": {
    id: "routes/banned";
    page: "/banned";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/api.admin.approve.ts": {
    id: "routes/api.admin.approve";
    page: "/api/admin/approve";
  };
  "routes/api.admin.change-role.ts": {
    id: "routes/api.admin.change-role";
    page: "/api/admin/change-role";
  };
  "routes/auth.login.ts": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.callback.ts": {
    id: "routes/auth.callback";
    page: "/api/auth/callback/authentik";
  };
  "routes/auth.logout.ts": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/pending": typeof import("./app/routes/pending.tsx");
  "routes/banned": typeof import("./app/routes/banned.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/api.admin.approve": typeof import("./app/routes/api.admin.approve.ts");
  "routes/api.admin.change-role": typeof import("./app/routes/api.admin.change-role.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login.ts");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.ts");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.ts");
};